/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./app/routes/__root";
import { Route as IndexImport } from "./app/routes/index";
import { Route as MoviesIndexImport } from "./app/routes/movies.index";
import { Route as MoviesIdImport } from "./app/routes/movies.$id";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const MoviesIndexRoute = MoviesIndexImport.update({
  path: "/movies/",
  getParentRoute: () => rootRoute,
} as any);

const MoviesIdRoute = MoviesIdImport.update({
  path: "/movies/$id",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/movies/$id": {
      id: "/movies/$id";
      path: "/movies/$id";
      fullPath: "/movies/$id";
      preLoaderRoute: typeof MoviesIdImport;
      parentRoute: typeof rootRoute;
    };
    "/movies/": {
      id: "/movies/";
      path: "/movies";
      fullPath: "/movies";
      preLoaderRoute: typeof MoviesIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  MoviesIdRoute,
  MoviesIndexRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movies/$id",
        "/movies/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/movies/$id": {
      "filePath": "movies.$id.tsx"
    },
    "/movies/": {
      "filePath": "movies.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
